#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMzk0MDIxNywianRpIjoiNzU4YjRiZGUtOTljYy00OTRkLTlhMzMtYzQyYzg4ZGZlYWRjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NiwibmJmIjoxNzMzOTQwMjE3LCJjc3JmIjoiNzU0NDY3ZTgtNzJiNi00NDBlLThlOTktYTQ2MTQ1YmU4NGRjIiwiZXhwIjoxNzMzOTQxMTE3fQ.oZgWxpLkuvHhvjxSLKwph0WX83NoyqNtMnj4iVca6jw

print(type(usuario.id), usuario.id)