"""Corigindo erros da tabela produtos

Revision ID: 02bc052586f5
Revises: fdd03488186b
Create Date: 2025-04-15 17:53:53.732768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02bc052586f5'
down_revision = 'fdd03488186b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=100), nullable=True))
        batch_op.drop_column('preco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
