"""Criando a tabela produtos e categorias

Revision ID: 152e8228fd8f
Revises: 
Create Date: 2024-11-25 19:43:04.349706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152e8228fd8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_categoria', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_categoria')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=50), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    op.drop_table('produtos')
    op.drop_table('categorias')
    # ### end Alembic commands ###
