"""adicionando a coluna telefone e tipo_de_usuario na coluna Usuario

Revision ID: 33c733832a16
Revises: a22c8230fbf6
Create Date: 2025-04-14 19:44:27.027241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33c733832a16'
down_revision = 'a22c8230fbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('Tipo_de_usuario', sa.Enum('comum', 'Administrador', name='tipo_usuario_enum'), nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('Tipo_de_usuario')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
