"""Adicionando a tabela de enderecos

Revision ID: 4ebb61c84da6
Revises: 9a091615b7b5
Create Date: 2024-11-27 14:02:14.957779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebb61c84da6'
down_revision = '9a091615b7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereços',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(100), nullable=False),
    sa.Column('numero', sa.String(50), nullable=False),
    sa.Column('complemento', sa.String(100), nullable=False),
    sa.Column('bairro', sa.String(100), nullable=False),
    sa.Column('cidade', sa.String(100), nullable=False),
    sa.Column('estado', sa.String(100), nullable=False),
    sa.Column('cep', sa.String(50), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereços')
    # ### end Alembic commands ###
