"""Adicionando tabela Tamanho_produtos

Revision ID: 5cd643234ee4
Revises: 02bc052586f5
Create Date: 2025-04-15 18:06:15.172735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd643234ee4'
down_revision = '02bc052586f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tamanhos_produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tamanhos_produtos')
    # ### end Alembic commands ###
