"""Corrigindo erros ortograficos

Revision ID: 6f7ceecceca0
Revises: 33c733832a16
Create Date: 2025-04-14 19:54:45.986855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f7ceecceca0'
down_revision = '33c733832a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column(
            'Tipo_de_usuario',
            new_column_name='tipo_de_usuario',
            existing_type=sa.Enum('comum', 'Administrador', name='tipo_usuario_enum'),
            nullable=False
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column(
            'tipo_de_usuario',
            new_column_name='Tipo_de_usuario',
            existing_type=mysql.ENUM('comum', 'Administrador'),
            nullable=False
    )


    # ### end Alembic commands ###
