"""Adicionando tabela PrecoProdutos, e corrigindo os nomes da classe usando boas praticas de CamelCase

Revision ID: b33921589dbd
Revises: 5cd643234ee4
Create Date: 2025-04-15 18:30:20.240493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33921589dbd'
down_revision = '5cd643234ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precos_produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tamanho_id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['tamanho_id'], ['tamanhos_produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precos_produtos')
    # ### end Alembic commands ###
