"""Adicionando e retirando colunas da tabela pedidos

Revision ID: bebc191839be
Revises: 6f7ceecceca0
Create Date: 2025-04-15 16:52:55.180893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bebc191839be'
down_revision = '6f7ceecceca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_do_pedido', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status_do_pedido', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('endereço_de_entrega_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('forma_de_pagamento', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.create_foreign_key(None, 'enderecos', ['endereço_de_entrega_id'], ['id'])
        batch_op.drop_column('total')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('total', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('valor_total')
        batch_op.drop_column('forma_de_pagamento')
        batch_op.drop_column('endereço_de_entrega_id')
        batch_op.drop_column('status_do_pedido')
        batch_op.drop_column('data_do_pedido')

    # ### end Alembic commands ###
